#*******************************************************************************
#
# Makefile for PtokaX.
#
# Run ./configure first; it writes config.mk, which this file includes.
# Everything below is platform-neutral -- all system knowledge lives in
# config.mk.
#
#   ./configure && make && make install
#
# Useful knobs:
#   make V=1                 show full compiler command lines
#   make -j8                 parallel build (no recursive make, so this is safe)
#   make DESTDIR=/tmp/stage install
#
#*******************************************************************************

ifeq ($(wildcard config.mk),)
$(error No config.mk found. Run ./configure first (./configure --help for options))
endif
include config.mk

#*******************************************************************************
# Quiet output; `make V=1` restores full command lines.
#*******************************************************************************
V ?= 0
ifeq ($(V),0)
  Q := @
  say = @printf '  %-8s %s\n' '$(1)' '$(2)'
else
  Q :=
  say =
endif

#*******************************************************************************
# Sources
#
# core/*.cpp is globbed and then filtered, so new sources are picked up without
# editing this file. The exclusions are the Windows-only translation units plus
# every database backend -- configure selects one back in via DB_SRC.
#*******************************************************************************
CORE_EXCLUDE := \
	core/PtokaX-win.cpp \
	core/ExceptionHandling.cpp \
	core/UpdateCheckThread.cpp \
	core/DB-SQLite.cpp \
	core/DB-PostgreSQL.cpp \
	core/DB-MySQL.cpp

SRCS_CXX := $(filter-out $(CORE_EXCLUDE),$(wildcard core/*.cpp)) $(DB_SRC)

ifneq ($(TINYXML_BUNDLED),)
SRCS_CXX += tinyxml/tinystr.cpp tinyxml/tinyxml.cpp \
            tinyxml/tinyxmlerror.cpp tinyxml/tinyxmlparser.cpp
endif

SRCS_C :=
ifneq ($(SKEIN),)
SRCS_C += skein/Optimized_32bit/skein.c skein/Optimized_32bit/skein_block.c
endif

BUILDDIR := build
OBJS := $(addprefix $(BUILDDIR)/,$(SRCS_CXX:.cpp=.o) $(SRCS_C:.c=.o))
DEPS := $(OBJS:.o=.d)

TARGET := PtokaX

#*******************************************************************************
# Flags
#
# The configure-chosen flags come first and the user's come last, so a value
# from the environment or the command line always wins.
#*******************************************************************************
DEPFLAGS := -MMD -MP

ALL_CPPFLAGS := -Icore $(SKEIN_CPPFLAGS) $(TINYXML_CPPFLAGS) $(FEATURE_DEFINES) \
                $(LUA_CFLAGS) $(ZLIB_CFLAGS) $(DB_CFLAGS) \
                $(CONF_CPPFLAGS) $(CPPFLAGS)

ALL_CXXFLAGS := $(CONF_OPTFLAGS) $(CONF_WARNFLAGS) $(PTHREAD_CFLAGS) \
                $(CONF_CXXFLAGS) $(CXXFLAGS)

ALL_CFLAGS   := $(CONF_OPTFLAGS) $(CONF_WARNFLAGS) $(PTHREAD_CFLAGS) \
                $(CONF_CFLAGS) $(CFLAGS)

ALL_LDFLAGS  := $(CONF_LDFLAGS) $(LDFLAGS)

ALL_LIBS     := $(LUA_LIBS) $(ZLIB_LIBS) $(DB_LIBS) $(TINYXML_LIBS) \
                $(ICONV_LIBS) $(DL_LIBS) $(SOCKET_LIBS) $(PTHREAD_LIBS) -lm \
                $(CONF_LIBS) $(LIBS)

#*******************************************************************************
# Build
#*******************************************************************************
.PHONY: all
all: $(TARGET)

$(TARGET): $(OBJS)
	$(call say,LINK,$@)
	$(Q)$(CXX) $(ALL_LDFLAGS) $(OBJS) -o $@ $(ALL_LIBS)

$(BUILDDIR)/%.o: %.cpp
	@mkdir -p $(@D)
	$(call say,CXX,$<)
	$(Q)$(CXX) $(ALL_CPPFLAGS) $(ALL_CXXFLAGS) $(DEPFLAGS) -c $< -o $@

$(BUILDDIR)/%.o: %.c
	@mkdir -p $(@D)
	$(call say,CC,$<)
	$(Q)$(CC) $(ALL_CPPFLAGS) $(ALL_CFLAGS) $(DEPFLAGS) -c $< -o $@

# Header dependencies, generated by the compiler. Replaces the hand-maintained
# per-object header lists the old makefiles carried.
-include $(DEPS)

#*******************************************************************************
# Install
#
# Every path is $(DESTDIR)-prefixed so a staged/packaging build cannot escape
# its staging root. Only the binary is installed: PtokaX resolves language/,
# cfg/, scripts/ and texts/ relative to its runtime config directory (-c), so
# there is no system data directory to populate.
#*******************************************************************************
.PHONY: install
install: $(TARGET)
	$(INSTALL) -d $(DESTDIR)$(bindir)
	$(INSTALL) -m 755 $(TARGET) $(DESTDIR)$(bindir)/$(TARGET)
	@echo ""
	@echo "  $(TARGET) installed to $(DESTDIR)$(bindir)/$(TARGET)"
	@echo ""
	@echo "  To let it bind ports below 1024, run (needs root):"
	@echo "      make setcap"
	@echo ""
	@echo "  Config files are not installed: PtokaX keeps cfg/, logs/, scripts/"
	@echo "  and texts/ under the directory given with -c (or \$$HOME/.PtokaX"
	@echo "  when run with -d). Seed one with:"
	@echo "      mkdir -p ~/.PtokaX/cfg"
	@echo "      cp -r cfg.example/* ~/.PtokaX/cfg/"
	@echo "      cp -r language       ~/.PtokaX/"
	@echo ""

.PHONY: uninstall
uninstall:
	rm -f $(DESTDIR)$(bindir)/$(TARGET)

# Deliberately separate from `install`: setcap needs root and would break a
# DESTDIR/packaging build, which is why the old makefile's inline call was wrong.
.PHONY: setcap
setcap:
	@if [ "$(HOST_OS)" != Linux ]; then \
		echo "setcap is Linux-only; on $(HOST_OS) run PtokaX as root or use a high port."; \
		exit 1; \
	fi
	setcap 'cap_net_bind_service=+ep' $(DESTDIR)$(bindir)/$(TARGET)
	@echo "$(TARGET) may now bind ports below 1024."
	@echo "Alternative, without capabilities:"
	@echo "    sysctl -w net.ipv4.ip_unprivileged_port_start=411"

#*******************************************************************************
# Checks and housekeeping
#*******************************************************************************
# -v returns inside the argv loop in core/PtokaX-nix.cpp, before any path
# resolution or mkdir, so this creates no files and opens no sockets.
.PHONY: check
check: $(TARGET)
	$(Q)./$(TARGET) -v

.PHONY: clean
clean:
	rm -rf $(BUILDDIR) $(TARGET)

.PHONY: distclean
distclean: clean
	rm -f config.mk config.log

.PHONY: config
config:
	$(Q)eval ./configure $(CONFIGURE_ARGS)

.PHONY: help
help:
	@echo "PtokaX $(PACKAGE_VERSION) -- make targets"
	@echo ""
	@echo "  all        build $(TARGET) (default)"
	@echo "  install    install to \$$(DESTDIR)\$$(bindir) = $(DESTDIR)$(bindir)"
	@echo "  uninstall  remove the installed binary"
	@echo "  setcap     allow binding ports < 1024 (Linux, needs root)"
	@echo "  check      smoke test the built binary"
	@echo "  clean      remove build output"
	@echo "  distclean  also remove config.mk and config.log"
	@echo "  config     re-run ./configure with the same options as last time"
	@echo ""
	@echo "Current configuration (from config.mk):"
	@echo "  prefix     $(prefix)"
	@echo "  compiler   $(CXX)"
	@echo "  Lua        $(LUA_VERSION)"
	@echo "  database   $(DB_BACKEND)"
	@echo "  tinyxml    $(if $(TINYXML_BUNDLED),bundled,system)"
	@echo "  Skein      $(if $(SKEIN),yes,no)"
	@echo ""
	@echo "  make V=1   show full compiler command lines"
