NGINX_PREFIX='/usr/local'
NGINX_USER='nginx'
NGINX_MODE='prefix'
BUILD_DIR='/usr/local/src/nginx'
TLS_PORT='5411'
PROXY_ADDR='127.0.0.1:5412'
TCP_PORT='411'
HUB='AHDev'
STATE_DIR=''
HUB_ADDR='livinglavish.duckdns.org'
CERT_METHOD='letsencrypt'
CERT=''
KEY=''
CERT_CUSTOM='no'
STREAM_DIR='/usr/local/nginx/conf/stream.d'
CONFD_DIR='/usr/local/nginx/conf/conf.d'
ENABLE_CONSOLE='yes'
CERT_CHALLENGE='dns'
