NGINX_PREFIX='/usr/local/nginx'
NGINX_USER='nginx'
NGINX_MODE='auto'
BUILD_DIR='/usr/local/src/nginx'
TLS_PORT='5411'
PROXY_ADDR='127.0.0.1:5412'
TCP_PORT='411'
HUB='ah'
STATE_DIR=''
HUB_ADDR='livinglavish.duckdns.org'
CERT_METHOD='existing'
CERT='/etc/letsencrypt/live/livinglavish.duckdns.org/fullchain.pem'
KEY='/etc/letsencrypt/live/livinglavish.duckdns.org/privkey.pem'
CERT_CUSTOM='no'
STREAM_DIR='/usr/local/nginx/conf/stream.d'
CONFD_DIR='/usr/local/nginx/conf/conf.d'
ENABLE_CONSOLE='yes'
CERT_CHALLENGE='http'
